### ISSUE TITLE
Error Detection Supersedes Valid Content Response

### ISSUE THREAD

**Issue by dahlbyk** [Dwolla/dwolla-v2-csharp#47]
https://developers.dwolla.com/guides/business-verified-customer/handle-verification-statuses#determining-verification-documents example response documents a scenario where `errors` is expected _along with_ valid content and a 200 OK response body. 

This regex matches on that response, suppressing valid `Content` (important to be able to repair the `Customer`) in the presence of `errors`:
https://github.com/Dwolla/dwolla-v2-csharp/blob/393fd173bdf88e48b49d5c7ffdfcb4535dbe846d/Dwolla.Client/Rest/ResponseBuilder.cs#L29-L31

Expected behavior: either...
- 200 OK response from `GET Customer` always deserializes the `Customer` into `RestResponse<Customer>.Content`. 
- 200 OK API response shouldn't include `errors`. In this case, the DBA required error is also communicated via `_links['upload-dba-document']`.

Actual behavior:
- 200 OK response from `GET Customer` returns a `RestResponse<Customer>` with `Content = null`.
- 200 OK response includes `errors`, which I don't recall seeing for other document-required scenarios.

**Comment by ShreyaThapa** [comment]
Hi @dahlbyk  -- thanks for reporting! We were table to test internally and confirm that this is a bug. The expected behavior is that the `Content` should always be populated for 200 Ok response even if it contains an `error` object.

We have logged a bug ticket on our end to work on a fix, however, we do not anticipate to have it rolled out this week or the next. 

In the meantime, feel free to clone the repo and update the logic so that you can continue using the SDK in your application. We also appreciate pull requests if you would like to contribute to the repo!

Thank you and Happy Holidays!

**Comment by dahlbyk** [comment]
We were able to patch and work around this: https://github.com/Stratafolio/dwolla-v2-csharp/tree/gh-47-hack.

But a more correct fix seems like it would need to add `_embedded` to `BaseResponse` so `errors` are available in the successful response.

**Comment by ShreyaThapa** [comment]
Thanks @dahlbyk!

Logging the proposed two-fold solution for reference:
- add `_embedded` to `BaseResponse`
- populate `Content` for all 200 Ok responses including ones that have an `error` object

**Comment by ShreyaThapa** [comment]
This issue has been fixed in the latest release [5.4.0](https://github.com/Dwolla/dwolla-v2-csharp/releases/tag/5.4.0).

**Comment by dahlbyk** [comment]
Great, thanks!

(Fixed in #48)
