### ISSUE TITLE
ResponseBuilder Can't Deserialize JSON "Value" to Decimal 

### ISSUE THREAD

**Issue by StevP116** [Dwolla/dwolla-v2-csharp#56]
In an attempt to retrieve a transfer from sandbox, using the Dwolla `TransferResponse` model, when I hit the `GET https://api.dwolla.com/transfers/{id}` endpoint, I get the following `DeserializationException` with error response:

`The JSON value could not be converted to System.Decimal. Path: $.amount.value | LineNumber: 0 | BytePositionInLine: 1174.`

This is the JSON amount data:
```
"amount": {
    "value": "31.25",
    "currency": "USD"
  }
```

The `DeserializationException` is coming from the `ResponseBuilder`. It is using a `JsonSerializerOptions` object that isn't configured to handle quoted numbers. The `JsonSerializerOptions` that the `RestClient` and `ResponseBuilder` are using is configured in the `DwollaClient`. Therefore, I don't believe there is anything we can do on our end to remedy this issue. 

Seems like a pretty simple fix would be to configure the default `JsonSerializerOptions` with `NumberHandling = JsonNumberHandling.AllowReadingFromString`.

**Comment by StevP116** [comment]
As a follow-up, [this](https://github.com/Dwolla/dwolla-v2-csharp/issues/53#issue-1655224157) might be really nice to have as well.

**Comment by StevP116** [comment]
**Update:** We found a workaround by creating an instance of `RestClient` and passed in a  customized `JsonSerializerOptions` object, then used reflection to invoke the internal `DwollaClient` constructor. Even still, having a fix for this would be nice, as using reflection is not ideal.

**Comment by jacob-ezlandlord** [comment]
We have been using version 5.4.0 of the Dwolla client with no issues, but when we tried to upgrade to the latest stable version (6.0.0), it seems like this bug was reintroduced.

We encountered the same deserialization error trying to hit `funding-sources/{id}/balance` and convert the response content to a `BalanceReponse`.

Is this known to still be an issue? Is it being addressed?

P.S. The reason we are trying to upgrade to the latest stable version is in light of Dwolla's upcoming changes involving HTTP/2. They seem to recommend updating to the latest versions of their clients to ensure we can handle their updates. It would be great if someone could comment on whether version 5.4.0 of this client is sufficient to be prepared for Dwolla's upcoming updates.

**Comment by ShreyaThapa** [comment]
Hi @StevP116 and @jacob-ezlandlord! Thank you both for bringing this issue to our attention and for your patience. We recognize that the `JsonSerializerOptions` in the SDK currently doesn't handle quoted numbers, leading to the errors you've encountered.

We're implementing @StevP116's suggestion to configure the `JsonSerializerOptions` with `JsonNumberHandling.AllowReadingFromString`. This change will allow numeric values returned as strings to be properly deserialized without requiring modifications to existing models like `TransferResponse` and `BalanceResponse`.

This fix is planned for the upcoming sprint. Once this update is live, the SDK will seamlessly support both quoted and unquoted numeric values, ensuring compatibility with any variations in API responses.

We appreciate your input and will keep you updated on the release! 🙏

**Comment by ShreyaThapa** [comment]
This has been released in the latest version - [Dwolla.Client v6.0.1](https://www.nuget.org/packages/Dwolla.Client). Special thanks to [StevP116](https://github.com/StevP116) for your contribution to this release! 👏 🙇‍♀️
