### ISSUE TITLE
Separate extra-response models from response models

### ISSUE THREAD

**Issue by ithielnor** [Dwolla/dwolla-v2-csharp#7]
There are now several models that are not directly returned by requests (e.g. `IavAccountHolders`, `IndustryClassification`, others on the way). 

To alleviate confusion, I think these should either be named or namespaced differently. A few suggestions:

- Modify DwollaClient to only allow TRes types that extend RootResponse (so no one can compile `GetAsync<IavAccountHolders>(...)` etc.)
- Move internal models into a namespace within responses: e.g. `Models.Responses.Internals`
- Or require every concrete class that extends RootResponse to be named `xxxxResponse`

Thoughts?

**Comment by therockstorm** [comment]
Rather than the second bullet, can we just move IavAccountHolders and IndustryClassifications to their respective response files? I think that'd make it clearer that they're not returned directly. Either that or we move them up a level to Dwolla.Client.Models. 

The third bullet would cause lots of breaking changes, which is fine this early, but would we then have to rename TokenResponse and ErrorResponse since they don't inherit BaseResponse? I don't like this option.

I like the first bullet since the compiler would do the work, but TokenResponse is unique and doesn't inherit from BaseResponse. We could make it, but the _links property would always be null.

**Comment by therockstorm** [comment]
I pushed up the change to move IndustryClassifications and IavAccountHolders since it wasn't a breaking change but open to other changes. Closing for now, feel free to reopen.

**Comment by ithielnor** [comment]
For the first bullet, we could use `RootResponse` instead of `BaseResponse on both TokenResponse and ErrorResponse. I'll make this change in another PR and hook it up in a new PR.

I do think it would be good to begin enforcing a naming convention on models for all new PRs. That way we have some consistency even if we have a few classes that will eventually need to be renamed.

**Comment by ithielnor** [comment]
Of course I just realized that `RootResponse` extends BaseResponse not the other way around. Perhaps an interface would be better.
